# Generated by Django 4.1.3 on 2022-12-02 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('emp_id', models.CharField(max_length=100)),
                ('phone', models.CharField(max_length=10)),
                ('e_addr', models.CharField(max_length=300)),
                ('wfh', models.BooleanField(default=False)),
                ('dept', models.CharField(max_length=100)),
            ],
        ),
    ]
